### ISSUE TITLE
"O MONSTRO TÁ SAINDO DA JAULA" como break para laços

### ISSUE THREAD

**Issue by Gutem** [birl-language/birl-language.github.io#15]

**Comment by eduardovpessoa** [comment]
Não seria "TÁ SAINDO DA JAULA O MONSTRO"?

Se bem que no birl-server o break tá como "SAI FILHO DA PUTA" rs.

**Comment by Gutem** [comment]
Verdade! É que escrevi no dialeto Yoda... rs
Pode ser implementado no `try... catch`.

**Comment by leonelsanchesdasilva** [comment]
Estamos reimplementando BIRL em https://github.com/DesignLiquido/delegua. Se quiserem sugerir a ideia lá, podem fazer por https://github.com/DesignLiquido/delegua/discussions.
