### ISSUE TITLE
Os tipos de dados não são montrões o suficiente

### ISSUE THREAD

**Issue by Rafagd** [birl-language/birl-language.github.io#2]
QUE CHAR, SHORT, INT, LONG O QUE PO TEM QUE SER FRANGO, MONSTRINHO, MONSTRO, MONSTRÃO BIRL

**Comment by DiegoCatalano** [comment]
Também podia ter os tipo:

whey, creatina, albumina

Variavel implicita: mutante, para aqueles que não querem ficar declarando whey, creatina, etc...

**Comment by lsabiao** [comment]
com certeza, isso é uma issue.

**Comment by lcfpadilha** [comment]
Opa! Na proxima versão vamos deixar os tipos de dados mais bodybuilders! 
BIRL

**Comment by marcosroriz** [comment]
CONCORDO TOTALMENTE. QUE PORRA É ESSA DE INT.
CADE O TRAPÉZIO DESCENDENTE ?

**Comment by fcannini** [comment]
Tem que ter um tipo "BATATA DOCE" na versão 2.0.

E tipos compostos (algo como uma struct de C ou um dictionary de python) porque comer só frango ou só batata doce não fica monstro!

**Comment by icaromsc** [comment]
podemos implementar o paradigma orientado a objetos nessa linguagem
 tu cria mutantes(classe) que podem receber herança de um monstrão(classe pai)
instancia um mutante: TÁ SAINDO DA JAULA O MONSTRO (nomeMutante)
interface : TRAPÉZIO DESCENDENTE
NomeMutante implements trapezio descendente

**Comment by fernandofranca** [comment]
Melhor issue aberta. Não consigo sugerir nada, tô chorando de rir.

**Comment by ghost** [comment]
BIRL orientado a objetos, como @icaromsc falou, VAI MUTANTE!!

**Comment by akaFTS** [comment]
PORRA! Tipos de dados monstros adicionados. SEGURA A GENTE!
