### ISSUE TITLE
Ficar monstro no Atom

### ISSUE THREAD

**Issue by cristianzsh** [birl-language/birl-language.github.io#24]
Que tal ficar monstrão usando o Atom?

<img src="http://i.imgur.com/8BRUnq9.png" />

Posso colocar o código no meu GitHub.

**Comment by KitsuneDev** [comment]
+1! Fazendo uma para Sublime Text 3 com autocomplete,... . Pf posta a sua!! Assim posso usar como base tb!!!

**Comment by odahcam** [comment]
+1 posta no Git e publica no APM pra gente instalar, tenho tema de sintaxe Monokai e já busquei mais de 13 vezes a linguagem Birl pra instalar no meu Atom e aperfeiçoar o tema pra linguagem, mas nunca achei. Seria bem legal ter finalmente reconhecimento pra essa linguagem monstro.

**Comment by cristianzsh** [comment]
Estarei publicando em breve... Desculpa pela demora :)

**Comment by cristianzsh** [comment]
Coloquei o código no meu GitHub: https://github.com/cristian-henrique/language-birl
Em breve colocarei para download via Atom :)

**Comment by odahcam** [comment]
Perfeito cara! Se aceita uma dica singela, usa o package [apm-publish](https://atom.io/packages/apm-publish) pra publicar no Atom, facilita bastante a vida.
