### ISSUE TITLE
ELSE IF = QUE NÃO VAI DAR O QUE?!

### ISSUE THREAD

**Issue by danhenriquesc** [birl-language/birl-language.github.io#3]
else if tinha que ser: QUE NÃO VAI DAR O QUE?!

**Comment by euclydesbsn** [comment]
Concordo IUAHIUAHIUAH elseif tinha que ter uma frase melhor, como essa

**Comment by felipelmota** [comment]
"QUE NAO VAI DAR O QUE?!" tá mais pro TRY :)

**Comment by akaFTS** [comment]
Valeu! Vamos adicionar na versão 1.1 da linguagem :)
